version: 2
updates:
  - directory: /backend
    package-ecosystem: pip
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - directory: /frontend
    package-ecosystem: npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      frontend-dev:
        dependency-type: development
        patterns:
          - "*"
      frontend-prod:
        dependency-type: production
        patterns:
          - "*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
